### ISSUE TITLE
Running action locally with package source

### ISSUE THREAD

**Issue by dgkf** [pharmaR/thevalidatoR#3]
_from discussion at R Validation Hub repos wg weekly standup_

As we may not use repository-side actions as the execution engine long term, it may be necessary to orchestrate runs somehow. To help ease this transition, it would be nice to know we can adapt the actions for a local run.

Can we test out using [actions `runner`](https://github.com/actions/runner) to run actions workflows "locally" in a way that they can be more easily orchestrated.

For now this would just be an informational task to help us decide if/when we should consider other orchestration tools and help us anticipate any growing pains if we have to transition.

**Comment by yannfeat** [comment]
Ok, now that we have a working workflow, I am going to test it on a local repository.

**Comment by yannfeat** [comment]
I have tested the workflow on a self-hosted runner successfully: https://github.com/yannfeat/thevalidatoR/actions/runs/8115570407
